apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data-pvc
  namespace: petitemaisonepouvante
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # 1 Go de stockage local alloué à la DB
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petitemaisonepouvante-db
  namespace: petitemaisonepouvante
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petitemaisonepouvante-db
  template:
    metadata:
      labels:
        app: petitemaisonepouvante-db
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "Password123!" # À sécuriser via un Secret plus tard
        volumeMounts:
        - name: mssqldata
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldata
        persistentVolumeClaim:
          claimName: mssql-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: petitemaisonepouvante-db
  namespace: petitemaisonepouvante
spec:
  selector:
    app: petitemaisonepouvante-db
  ports:
  - port: 1433
    targetPort: 1433